// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFy-61NJcrQCpJwzmZfzQ0qSxO9majuCE',
    appId: '1:241231240323:web:e2a0284ae64aa5e4e14fb6',
    messagingSenderId: '241231240323',
    projectId: 'testfire-5a5d6',
    authDomain: 'testfire-5a5d6.firebaseapp.com',
    storageBucket: 'testfire-5a5d6.appspot.com',
    measurementId: 'G-X8SEL61ZLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTQAttFc8FYWlQMA_EcjSru3o4UAczBM',
    appId: '1:241231240323:android:e0e57cb2a8571220e14fb6',
    messagingSenderId: '241231240323',
    projectId: 'testfire-5a5d6',
    storageBucket: 'testfire-5a5d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV2Hjhs9B-64VTWxoVcPRUb_UodzLrVfs',
    appId: '1:241231240323:ios:3c94a7f8a51cf30ae14fb6',
    messagingSenderId: '241231240323',
    projectId: 'testfire-5a5d6',
    storageBucket: 'testfire-5a5d6.appspot.com',
    iosBundleId: 'com.example.testfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV2Hjhs9B-64VTWxoVcPRUb_UodzLrVfs',
    appId: '1:241231240323:ios:18179b90694b8089e14fb6',
    messagingSenderId: '241231240323',
    projectId: 'testfire-5a5d6',
    storageBucket: 'testfire-5a5d6.appspot.com',
    iosBundleId: 'com.example.testfirebase.RunnerTests',
  );
}
